# This Actions workflow creates a new Github Release on push to master.
# Please pin all actions to commit SHA.

name: Create Release

on:
  push:
    branches: [main]

jobs:
  create-version:
    name: Version and Release
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout Code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: Determine Version
        id: determine-version
        uses: paulhatch/semantic-version@3d2ea28b25c9a892b07cd24b5675300b701fcef5

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          tag_name: ${{ steps.determine-version.outputs.version_tag }}
          name: ${{ steps.determine-version.outputs.version_tag }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}
